apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: mkz8fzn7h-python
  janus-idp.io/tekton: mkz8fzn7h-python
  backstage.io/kubernetes-id: mkz8fzn7h-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mkz8fzn7h-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
